version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /Makefile
    destination: /opt/app/
hooks:
  BeforeInstall:
    - location: install
      timeout: 300
      runas: root
    - location: start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop
      timeout: 300
      runas: root

