version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install
      timeout: 300
      runas: ec2-user
    - location: start
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop
      timeout: 300
      runas: ec2-user

